steps:
- label: ":kubernetes: Running on k8s agents!"
  agents:
    queue: kubernetes
  plugins:
    - kubernetes:
        gitEnvFrom:
          - secretRef: { name: my-private-git-ssh-key }
        podSpec:
          containers:
            - image: alpine/k8s:1.27.5
              command: [kubectl]
              args:
                - "version"
                - "--short"
              resources:
                limits:
                  cpu: "100m"
                  memory: "128Mi"
