name: "Kubernetes example pipeline"
steps:
  - label: ":buildkite: Upload pipeline definition"
    command: "buildkite-agent pipeline upload .buildkite/pipeline.yml"
    agents:
      queue: kubernetes
